### PR TITLE
Add Jenkinsfile

### PR DESCRIPTION
**Pull request by surminus**

### CODE REVIEW

**Comment by afda16** [comment]
Does it need to run with the new Ruby version?

**Comment by surminus** [comment]
That needs a separate fix up, PR incoming

**Comment by surminus** [comment]
https://github.com/gds-operations/vcloud-net_launcher/pull/75 should fix these test failures

**Comment by surminus** [comment]
Closing this in lieu of https://github.com/gds-operations/vcloud-net_launcher/pull/74

**Pull request closed without merging**
